feat: warn on unknown schema types
sanity-io/sanity-plugin-documents-pane pull request #31
Opened 2023-01-28 06:15 UTC by nkgentile

When an unknown schema type is encountered as an incoming reference, warn the user and prompt to unset the reference

<img width="820" alt="Screenshot 2023-01-27 at 10 14 31 PM" src="https://user-images.githubusercontent.com/2839301/215250110-53d46f48-a890-4fd8-bc7a-314073b24aaa.png">

2023-01-28 17:18 UTC, nkgentile commented
Just realizing that incoming references isn't the only way that folks might use this plugin, so I can remove the action button

2023-01-31 08:49 UTC, snorrees requested changes

2023-01-31 08:49 UTC, snorrees commented on src/Documents.tsx
> +        // TODO: does this need to account for a draft?
I'd rather see you figure this todo out before mreging, it will just leave use wondering in the future.

2023-01-31 09:10 UTC, snorrees requested changes

2023-02-02 12:40 UTC, snorrees approved these changes

2023-02-02 12:41 UTC, merged